name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Pester
        shell: pwsh
        run: |
          $config = New-PesterConfiguration
          $config.CodeCoverage.Enabled = $true
          $config.Output.Verbosity = 'Detailed'
          $config.TestResult.Enabled = $true
          Invoke-Pester -Configuration $config
